### ISSUE TITLE
xkcd command doesn't work due to bad link

### ISSUE THREAD

**Issue by pep7** [molly/GorillaBot#60]
Use this url
https://c.xkcd.com/random/comic/

instead of
http://c.xkcd.com/random/comic/:

02:47:41 AM - Executor - INFO: http://c.xkcd.com/random/comic/: Not Found
02:47:41 AM - Executor - ERROR: Couldn't get random xkcd comic.

 !xkcd
anonbot Sorry, I'm broken. Tell GorillaWarfare to fix me.

also perhaps consider changing the error message from "tell GorillaWarfare to fix me" to "change settings in such and such file"
I've been looking for where in the source the xkcd url is changed. :P

It was in link.py line 97 approx

if len(m.line) == 1:
        url = "http://c.xkcd.com/random/comic/"   <-- this needs changing to https and it will work
        html = get_url(m, url)
        message = xkcd_direct(html)

**Comment by molly** [comment]
Closed by molly/GorillaBot/pull/61
